import "@/app/globals.css"
import "@/styles/typography.css"
import { dir } from "i18next"
// import { languages } from "@/i18n/settings"
import { Inter } from "next/font/google"
import { FooterBase } from "@/components/layout/FooterBase"
// import { useTranslation } from "@/i18n"
import NavBase from "@/components/layout/NavBase"
import { ThemeProvider } from "@/components/layout/ThemeProvider"
import NextAuthProvider from "@/components/layout/NextAuthProvider"
import { JSX } from "react"

const inter = Inter({ subsets: ["latin"] })

// export async function generateStaticParams(): Promise<
//   Array<Record<string, string>>
// > {
//   return languages.map(lng => ({ lng }))
// }

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: { lng: string }
}): Promise<JSX.Element> {
  const { lng } = await params
  // const { t } = await useTranslation(lng, "footer")

  return (
    <html lang={lng} dir={dir(lng)} suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextAuthProvider>
            <NavBase />
            {children}
            {/* <FooterBase t={t} lng={lng} /> */}
            {/* INFO: Have to remove t={t} from here because useTranslation be used in a async component */}
            <FooterBase lng={lng} />
          </NextAuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
